### ISSUE TITLE
Use of rubyzip

### ISSUE THREAD

**Issue by Ryngo** [jugyo/eeepub#35]
Hi, 
I came across a problem with eeepub and had an error message looking like :

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- zip/zip (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/eeepub-0.8.1/lib/eeepub/ocf.rb:1:in `<top (required)>'
```

In fact, it turns out that the last versions of rubyzip need to be called like this :
`require 'zip'`
instead of this
`require 'zip/zip'`
as is done in the file /lib/eeepub/ocf.rb, line 1.
This fixed the bug. However I'm not very skilled in Ruby, so I merely post this here.
Hope it can be useful !

**Comment by nurettin** [comment]
Workaround:

```
gem install zip-zip
```

**Comment by n3f4s** [comment]
Hi, I came across the same error. Why is it not fixed (I shouldn't have to use workaround for an error that was reported 2 years ago) ?

**Comment by Merovex** [comment]
I forked this and am using it as a dependency in another gem.

https://github.com/Merovex/eeepub

**Comment by harsh183** [comment]
Still broken as of today. Add `zip-zip` to my `Gemfile` fixed it. This can be fixed by adding it as an dependency.
